/** Declaration file generated by dts-gen */

export function exportFile(filename: any, opts: any, callback: any): void;

export function exportStream(ws: any, opts: any, callback: any): void;

export function importFile(filename: any, opts: any, callback: any): any;

export function importStream(rs: any, opts: any, callback: any): any;

export function previewCSVFile(filename: any, opts: any, callback: any): void;

export function previewStream(rs: any, opts: any, callback: any): void;

export function previewURL(u: any, opts: any, callback: any): any;

